import React from 'react';

const LegalSection: React.FC<{ title: string; icon: string; children: React.ReactNode }> = ({ title, icon, children }) => (
    <div className="bg-secondary-bg p-6 rounded-lg border border-border-dark animate-fade-in-down mb-8">
        <div className="flex items-center mb-4">
            <span className="material-symbols-outlined text-3xl text-accent-primary">{icon}</span>
            <h2 className="text-2xl font-bold text-text-heading ml-3">{title}</h2>
        </div>
        <div className="text-base text-text-muted-1 space-y-4 leading-relaxed prose prose-invert prose-p:text-text-muted-1 prose-strong:text-text-body prose-a:text-accent-secondary prose-h4:text-text-heading">
            {children}
        </div>
    </div>
);

export const Legal: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto py-8 px-4 animate-fade-in">
      <h1 className="text-4xl font-extrabold text-text-heading text-center mb-10">Legal & Privacy</h1>

      <LegalSection title="Disclaimer & Limitation of Liability" icon="gavel">
        <p>
          Nolvaryn is provided "as is" and is intended for informational purposes only. It should be used as an aid in identifying potential email-based threats, not as a definitive judgment or a substitute for professional cybersecurity advice or commercial security solutions.
        </p>
        <p>
          The analysis and risk score are generated by an AI model and may contain inaccuracies or fail to identify novel or highly sophisticated threats. The creators of Nolvaryn shall not be held liable for any damages or losses, direct or indirect, arising from the use of, or reliance on, the information provided by this tool. You are solely responsible for your actions and security practices. Always exercise extreme caution when handling suspicious emails and attachments.
        </p>
      </LegalSection>

      <LegalSection title="Privacy Policy" icon="policy">
        <p>
          <strong>We respect your privacy.</strong> This policy outlines what data we process when you use Nolvaryn. We do not collect any personal information, cookies, or tracking data.
        </p>
        
        <h4>Third-Party Services & Data Sharing</h4>
        <p>To provide a comprehensive analysis, Nolvaryn utilizes specialized third-party services. We only share the minimum data necessary for each service to function:</p>
        <ul className="list-disc list-inside space-y-3">
            <li>
                <strong>AI Analysis (Google Gemini):</strong> The full content of the uploaded <code className="bg-primary-bg text-accent-secondary px-1 py-0.5 rounded-md text-sm">.eml</code> file is sent to the Google Gemini API. According to <a href="https://cloud.google.com/vertex-ai/docs/generative-ai/data-governance" target="_blank" rel="noopener noreferrer">Google's Generative AI data governance policies</a>, this data is processed ephemerally and is not used to train their models.
            </li>
            <li>
                <strong>IP Geolocation (ipwho.is):</strong> Any public IP addresses found within the email's headers or body are sent to the <a href="https://ipwho.is/privacy" target="_blank" rel="noopener noreferrer">ipwho.is</a> service. This is done to retrieve geolocation and network data (like the city, country, and ISP), providing crucial context about the email's travel path. No other information from your email is shared with this service.
            </li>
        </ul>

        <p>
          <strong>Our Data Handling:</strong> We do <strong>not</strong> store, log, or retain the content of your uploaded files or the resulting analysis reports on our servers. The analysis runs on our serverless backend in memory and is discarded after the response is returned to your browser. The report is held only in your browser's memory for the duration of your session.
        </p>
        
        <p>
          <strong>Disclaimer:</strong> We have chosen these providers based on their stated commitment to privacy and security. However, Nolvaryn cannot independently verify or guarantee their data handling practices. By using Nolvaryn, you acknowledge and agree to the respective privacy policies of these third-party services.
        </p>
        
        <p>
          <strong>Warning Regarding Sensitive Information:</strong> For your own security, we strongly advise against uploading emails that contain highly sensitive personal, financial, or confidential information (e.g., passwords, social security numbers, credit card details, proprietary business data). Please review the email content and redact sensitive information before uploading.
        </p>
      </LegalSection>
      
       <LegalSection title="Terms of Service" icon="article">
        <p>
          By using Nolvaryn, you agree to the following terms:
        </p>
        <ul className="list-disc list-inside space-y-2">
            <li>You will only use this service to analyze emails for which you have the right to do so.</li>
            <li>You will not use this service for any malicious or unlawful purpose.</li>
            <li>You understand that the service is automated and may not be 100% accurate.</li>
            <li>You agree to the terms outlined in the Disclaimer and Privacy Policy.</li>
        </ul>
        <p>
            We reserve the right to modify these terms or suspend the service at any time.
        </p>
      </LegalSection>

    </div>
  );
};
